# see: https://github.com/pages-themes/cayman
theme: jekyll-theme-cayman
repository: chirimen-oh/tutorials
title: '<a href="/" style="color: white">CHIRIMEN チュートリアル</a>'
description: >-
  <a href="https://chirimen.org/" style="color: white">CHIRIMEN</a>を初めて使う方向けの <a href="https://tutorial.chirimen.org/" style="color: white">チュートリアル集</a> です<br>
  <a href="https://tutorial.chirimen.org/" style="color: white">目次のページ</a> からチュートリアルの各ページをご覧ください<br>
  <a href="/raspi3/ja/" style="color: white">CHIRIMEN for Raspberry Pi 3 用チュートリアル</a><br>
   <a href="/ty51822r3/ja" style="color: white">CHIRIMEN for  TY51822r3 用チュートリアルページ</a>
  Enjoy <a href="/raspi3/en/" style="color: white">Tutorials for CHIRIMEN for Raspberry Pi 3</a>
show_downloads: false
# google_analytics:
include:
  - _redirects

# Use CommonMarkGhPages for Markdown parser (after v172)
# https://github.com/github/jekyll-commonmark-ghpages
# https://github.com/github/pages-gem/releases/tag/v172
markdown: CommonMarkGhPages
commonmark:
  options:
    - FOOTNOTES
    - TABLE_PREFER_STYLE_ATTRIBUTES
  extensions:
    - strikethrough
    - autolink
    - table

# Use Kramdown for Markdown parser (obsolete)
# https://help.github.com/articles/configuring-jekyll/
# markdown: kramdown
# kramdown:
#   input: GFM
#   hard_wrap: false
#   math_engine: mathjax
#   syntax_highlighter: rouge
# gfm_quirks: paragraph_end
