# see: https://github.com/pages-themes/cayman
theme: jekyll-theme-cayman
repository: chirimen-oh/tutorials
title: '[CHIRIMEN チュートリアル](https://tutorial.chirimen.org/)'
description: '[CHIRIMEN](https://chirimen.org/) for Raspberry Pi 3 を始めて使う方向けの [チュートリアル集](https://tutorial.chirimen.org/raspberrypi/ja/) をご覧頂けます'
show_downloads: false
# google_analytics:
