# see: https://github.com/pages-themes/cayman
theme: jekyll-theme-cayman
repository: chirimen-oh/tutorials
title: '<a href="/" style="color: white">CHIRIMEN チュートリアル</a>'
description: >-
  ブラウザからハードを制御する <a href="https://chirimen.org/" style="color: white">CHIRIMEN</a> のチュートリアル集です<br>
  対応ボード別チュートリアル: <a href="/raspi3/" style="color: white">Raspberry Pi</a>
  / 
  <a href="/ty51822r3/" style="color: white">TY51822r3</a>
  / 
  <a href="https://chirimen.org/chirimen-micro-bit/" style="color: white">micro:bit</a>
show_downloads: false
# google_analytics:
include:
  - _redirects

# configs for GitHub Pages defult plugins
# https://help.github.com/en/articles/configuring-jekyll-plugins
# https://github.com/benbalter/jekyll-readme-index
readme_index:
  remove_originals: true

# Use CommonMarkGhPages for Markdown parser (after v172)
# https://github.com/github/jekyll-commonmark-ghpages
# https://github.com/github/pages-gem/releases/tag/v172
markdown: CommonMarkGhPages
commonmark:
  options:
    - FOOTNOTES
    - TABLE_PREFER_STYLE_ATTRIBUTES
  extensions:
    - strikethrough
    - autolink
    - table

# Use Kramdown for Markdown parser (obsolete)
# https://help.github.com/articles/configuring-jekyll/
# markdown: kramdown
# kramdown:
#   input: GFM
#   hard_wrap: false
#   math_engine: mathjax
#   syntax_highlighter: rouge
# gfm_quirks: paragraph_end

# Polyglot: Multilingual (i18n) support
# https://github.com/untra/polyglot
languages: ["ja", "en"]
default_lang: "ja"
exclude_from_localization: ["assets", "raspi3/examples"]
parallel_localization: true

# Jekyll Cloudinary Liquid tag plug-in
# https://nhoizey.github.io/jekyll-cloudinary/
# https://cloudinary.com/blog/how_i_used_cloudinary_to_solve_responsive_image_needs_in_my_jekyll_website_and_shared_the_magic_in_a_plugin
cloudinary:
  cloud_name: chirimen
  # only_prod: true
  verbose: false
  origin_url: https://tutorial.chirimen.org
  presets:
    default:
      min_width: 400
      max_width: 2000
      fallback_max_width: 1000
      steps: 9
      sizes: "(min-width: 72rem) 60rem, 90vw"
    full:
      min_width: 400
      max_width: 2000
      fallback_max_width: 1000
      steps: 9
      sizes: "(min-width: 72rem) 72rem, 100vw"
      attributes:
        class: full
    half:
      min_width: 200
      max_width: 1000
      fallback_max_width: 600
      steps: 5
      sizes: "(min-width: 36rem) 30rem, 50vw"
      attributes:
        class: half
    small:
      min_width: 200
      max_width: 800
      fallback_max_width: 400
      steps: 4
      sizes: "(min-width: 36rem) 20rem, 30vw"
      attributes:
        class: small
